# Generated by Django 3.2 on 2022-12-03 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_parent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
