# Generated by Django 3.2 on 2022-12-24 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_alter_message_reciever'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reciever',
        ),
        migrations.AddField(
            model_name='message',
            name='recievers',
            field=models.ManyToManyField(related_name='messages_recievers', to=settings.AUTH_USER_MODEL),
        ),
    ]
