# Generated by Django 3.2 on 2022-12-28 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_chat_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='hide_user',
            field=models.ManyToManyField(related_name='room_hide', to=settings.AUTH_USER_MODEL),
        ),
    ]
