# Generated by Django 3.2 on 2022-12-29 08:35

import chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_chat_hide_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactOneToOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactOneToOnes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatOneToOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(default=chat.models.UniqueGeneratorOneToOne, max_length=35)),
                ('hide', models.BooleanField(default=False)),
                ('hide_user', models.ManyToManyField(related_name='chatOneToOne_hide', to=settings.AUTH_USER_MODEL)),
                ('messages', models.ManyToManyField(blank=True, to='chat.Message')),
                ('participants', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatOneToOne', to='chat.contactonetoone')),
            ],
        ),
    ]
