# Generated by Django 3.2 on 2022-12-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chatonetoone_contactonetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatonetoone',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='chatonemessages', to='chat.Message'),
        ),
    ]
